// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovelVision.Services.Visualization.Infrastructure.Persistence;

#nullable disable

namespace NovelVision.Services.Visualization.Infrastructure.Migrations
{
    [DbContext(typeof(VisualizationDbContext))]
    [Migration("20260129174443_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("visualization")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NovelVision.Services.Visualization.Domain.Aggregates.VisualizationJobAggregate.GeneratedImage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("ExternalJobId")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ExternalJobId");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("GeneratedAt");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit")
                        .HasColumnName("IsSelected");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("JobId");

                    b.Property<int>("Provider")
                        .HasColumnType("int")
                        .HasColumnName("Provider");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_GeneratedImages_GeneratedAt");

                    b.HasIndex("IsSelected")
                        .HasDatabaseName("IX_GeneratedImages_IsSelected")
                        .HasFilter("[IsSelected] = 1 AND [IsDeleted] = 0");

                    b.HasIndex("JobId")
                        .HasDatabaseName("IX_GeneratedImages_JobId");

                    b.ToTable("GeneratedImages", "visualization");
                });

            modelBuilder.Entity("NovelVision.Services.Visualization.Domain.Aggregates.VisualizationJobAggregate.VisualizationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BookId");

                    b.Property<Guid?>("ChapterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ChapterId");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CompletedAt");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("ExternalJobId")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ExternalJobId");

                    b.Property<Guid?>("PageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PageId");

                    b.Property<int>("PreferredProvider")
                        .HasColumnType("int")
                        .HasColumnName("PreferredProvider");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("Priority");

                    b.Property<DateTime?>("ProcessingStartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ProcessingStartedAt");

                    b.Property<int>("Trigger")
                        .HasColumnType("int")
                        .HasColumnName("Trigger");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("Version");

                    b.Property<string>("_errorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("ErrorMessage");

                    b.Property<int>("_retryCount")
                        .HasColumnType("int")
                        .HasColumnName("RetryCount");

                    b.Property<int>("_status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("BookId")
                        .HasDatabaseName("IX_VisualizationJobs_BookId");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_VisualizationJobs_CreatedAt");

                    b.HasIndex("PageId")
                        .HasDatabaseName("IX_VisualizationJobs_PageId")
                        .HasFilter("[PageId] IS NOT NULL");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_VisualizationJobs_UserId");

                    b.HasIndex("_status")
                        .HasDatabaseName("IX_VisualizationJobs_Status");

                    b.HasIndex("_status", "Priority", "CreatedAt")
                        .IsDescending(false, true, false)
                        .HasDatabaseName("IX_VisualizationJobs_Queue");

                    b.ToTable("VisualizationJobs", "visualization");
                });

            modelBuilder.Entity("NovelVision.Services.Visualization.Domain.Aggregates.VisualizationJobAggregate.GeneratedImage", b =>
                {
                    b.HasOne("NovelVision.Services.Visualization.Domain.Aggregates.VisualizationJobAggregate.VisualizationJob", null)
                        .WithMany("Images")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("NovelVision.Services.Visualization.Domain.ValueObjects.PromptData", "PromptData", b1 =>
                        {
                            b1.Property<Guid>("GeneratedImageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("EnhancedPrompt")
                                .IsRequired()
                                .HasMaxLength(10000)
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PromptData_EnhancedPrompt");

                            b1.Property<string>("NegativePrompt")
                                .HasMaxLength(5000)
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PromptData_NegativePrompt");

                            b1.Property<string>("OriginalText")
                                .IsRequired()
                                .HasMaxLength(10000)
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PromptData_OriginalText");

                            b1.Property<string>("Parameters")
                                .IsRequired()
                                .HasMaxLength(5000)
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PromptData_Parameters");

                            b1.Property<string>("Style")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("PromptData_Style");

                            b1.Property<int>("TargetModel")
                                .HasColumnType("int")
                                .HasColumnName("PromptData_TargetModel");

                            b1.HasKey("GeneratedImageId");

                            b1.ToTable("GeneratedImages", "visualization");

                            b1.WithOwner()
                                .HasForeignKey("GeneratedImageId");
                        });

                    b.OwnsOne("NovelVision.Services.Visualization.Domain.ValueObjects.ImageMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("GeneratedImageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("BlobPath")
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasColumnName("BlobPath");

                            b1.Property<long>("FileSizeBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("FileSizeBytes");

                            b1.Property<int>("Format")
                                .HasColumnType("int")
                                .HasColumnName("Format");

                            b1.Property<int>("Height")
                                .HasColumnType("int")
                                .HasColumnName("Height");

                            b1.Property<string>("ThumbnailUrl")
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("ThumbnailUrl");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("ImageUrl");

                            b1.Property<int>("Width")
                                .HasColumnType("int")
                                .HasColumnName("Width");

                            b1.HasKey("GeneratedImageId");

                            b1.ToTable("GeneratedImages", "visualization");

                            b1.WithOwner()
                                .HasForeignKey("GeneratedImageId");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("PromptData")
                        .IsRequired();
                });

            modelBuilder.Entity("NovelVision.Services.Visualization.Domain.Aggregates.VisualizationJobAggregate.VisualizationJob", b =>
                {
                    b.OwnsOne("NovelVision.Services.Visualization.Domain.ValueObjects.PromptData", "_promptData", b1 =>
                        {
                            b1.Property<Guid>("VisualizationJobId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("EnhancedPrompt")
                                .IsRequired()
                                .HasMaxLength(10000)
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PromptData_EnhancedPrompt");

                            b1.Property<string>("NegativePrompt")
                                .HasMaxLength(5000)
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PromptData_NegativePrompt");

                            b1.Property<string>("OriginalText")
                                .IsRequired()
                                .HasMaxLength(10000)
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PromptData_OriginalText");

                            b1.Property<string>("Parameters")
                                .IsRequired()
                                .HasMaxLength(5000)
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PromptData_Parameters");

                            b1.Property<string>("Style")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("PromptData_Style");

                            b1.Property<int>("TargetModel")
                                .HasColumnType("int")
                                .HasColumnName("PromptData_TargetModel");

                            b1.HasKey("VisualizationJobId");

                            b1.ToTable("VisualizationJobs", "visualization");

                            b1.WithOwner()
                                .HasForeignKey("VisualizationJobId");
                        });

                    b.OwnsOne("NovelVision.Services.Visualization.Domain.ValueObjects.GenerationParameters", "Parameters", b1 =>
                        {
                            b1.Property<Guid>("VisualizationJobId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("AspectRatio")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Parameters_AspectRatio");

                            b1.Property<double?>("CfgScale")
                                .HasColumnType("float")
                                .HasColumnName("Parameters_CfgScale");

                            b1.Property<string>("Quality")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Parameters_Quality");

                            b1.Property<string>("Sampler")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Parameters_Sampler");

                            b1.Property<int?>("Seed")
                                .HasColumnType("int")
                                .HasColumnName("Parameters_Seed");

                            b1.Property<string>("Size")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Parameters_Size");

                            b1.Property<int?>("Steps")
                                .HasColumnType("int")
                                .HasColumnName("Parameters_Steps");

                            b1.Property<bool>("Upscale")
                                .HasColumnType("bit")
                                .HasColumnName("Parameters_Upscale");

                            b1.HasKey("VisualizationJobId");

                            b1.ToTable("VisualizationJobs", "visualization");

                            b1.WithOwner()
                                .HasForeignKey("VisualizationJobId");
                        });

                    b.OwnsOne("NovelVision.Services.Visualization.Domain.ValueObjects.TextSelection", "TextSelection", b1 =>
                        {
                            b1.Property<Guid>("VisualizationJobId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("ChapterId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("TextSelection_ChapterId");

                            b1.Property<string>("ContextAfter")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("TextSelection_ContextAfter");

                            b1.Property<string>("ContextBefore")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("TextSelection_ContextBefore");

                            b1.Property<int>("EndPosition")
                                .HasColumnType("int")
                                .HasColumnName("TextSelection_EndPosition");

                            b1.Property<Guid>("PageId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("TextSelection_PageId");

                            b1.Property<string>("SelectedText")
                                .IsRequired()
                                .HasMaxLength(5000)
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("TextSelection_SelectedText");

                            b1.Property<int>("StartPosition")
                                .HasColumnType("int")
                                .HasColumnName("TextSelection_StartPosition");

                            b1.HasKey("VisualizationJobId");

                            b1.ToTable("VisualizationJobs", "visualization");

                            b1.WithOwner()
                                .HasForeignKey("VisualizationJobId");
                        });

                    b.Navigation("Parameters")
                        .IsRequired();

                    b.Navigation("TextSelection");

                    b.Navigation("_promptData");
                });

            modelBuilder.Entity("NovelVision.Services.Visualization.Domain.Aggregates.VisualizationJobAggregate.VisualizationJob", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
