"""Initial_SQLite

Revision ID: 29678a714c32
Revises: 
Create Date: 2026-01-15 19:35:12.699174
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29678a714c32'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('book_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('age', sa.String(length=50), nullable=True),
    sa.Column('height', sa.String(length=50), nullable=True),
    sa.Column('build', sa.String(length=100), nullable=True),
    sa.Column('ethnicity', sa.String(length=100), nullable=True),
    sa.Column('face_shape', sa.String(length=100), nullable=True),
    sa.Column('skin', sa.String(length=100), nullable=True),
    sa.Column('hair', sa.String(length=200), nullable=True),
    sa.Column('eyes', sa.String(length=100), nullable=True),
    sa.Column('facial_features', sa.Text(), nullable=True),
    sa.Column('appearance', sa.Text(), nullable=True),
    sa.Column('default_clothing', sa.Text(), nullable=True),
    sa.Column('accessories', sa.Text(), nullable=True),
    sa.Column('distinguishing_features', sa.Text(), nullable=True),
    sa.Column('first_appearance_page', sa.Integer(), nullable=True),
    sa.Column('first_appearance_chapter', sa.Integer(), nullable=True),
    sa.Column('appearance_count', sa.Integer(), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=True),
    sa.Column('reference_image_url', sa.String(length=500), nullable=True),
    sa.Column('reference_prompt', sa.Text(), nullable=True),
    sa.Column('base_prompt', sa.Text(), nullable=True),
    sa.Column('embedding_vector', sa.JSON(), nullable=True),
    sa.Column('is_established', sa.String(length=1), nullable=True),
    sa.Column('generation_count', sa.Integer(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_characters_book_id'), ['book_id'], unique=False)
        batch_op.create_index('ix_characters_book_id_name', ['book_id', 'name'], unique=False)
        batch_op.create_index('ix_characters_importance', ['importance'], unique=False)

    op.create_table('prompt_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('book_id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=True),
    sa.Column('chapter_id', sa.String(length=36), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('chapter_number', sa.Integer(), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=True),
    sa.Column('context_before', sa.Text(), nullable=True),
    sa.Column('context_after', sa.Text(), nullable=True),
    sa.Column('enhanced_prompt', sa.Text(), nullable=False),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.Column('target_model', sa.String(length=50), nullable=False),
    sa.Column('style', sa.String(length=100), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('scene_type', sa.String(length=50), nullable=True),
    sa.Column('detected_characters', sa.JSON(), nullable=True),
    sa.Column('detected_objects', sa.JSON(), nullable=True),
    sa.Column('detected_location', sa.String(length=200), nullable=True),
    sa.Column('mood', sa.String(length=100), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('consistency_score', sa.Float(), nullable=True),
    sa.Column('complexity_score', sa.Float(), nullable=True),
    sa.Column('generated_image_url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('generation_status', sa.String(length=50), nullable=True),
    sa.Column('generation_error', sa.Text(), nullable=True),
    sa.Column('generation_duration_ms', sa.Integer(), nullable=True),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('was_regenerated', sa.Integer(), nullable=True),
    sa.Column('is_selected', sa.String(length=1), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_history_book_id'), ['book_id'], unique=False)
        batch_op.create_index('ix_prompt_history_book_page', ['book_id', 'page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_history_chapter_id'), ['chapter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_history_page_id'), ['page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_history_page_number'), ['page_number'], unique=False)
        batch_op.create_index('ix_prompt_history_status', ['generation_status'], unique=False)
        batch_op.create_index('ix_prompt_history_text_hash', ['text_hash'], unique=False)

    op.create_table('scenes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('book_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location_type', sa.String(length=100), nullable=True),
    sa.Column('setting_type', sa.String(length=100), nullable=True),
    sa.Column('architecture', sa.Text(), nullable=True),
    sa.Column('materials', sa.Text(), nullable=True),
    sa.Column('colors', sa.JSON(), nullable=True),
    sa.Column('textures', sa.Text(), nullable=True),
    sa.Column('atmosphere', sa.Text(), nullable=True),
    sa.Column('mood', sa.String(length=100), nullable=True),
    sa.Column('default_lighting', sa.String(length=200), nullable=True),
    sa.Column('light_sources', sa.JSON(), nullable=True),
    sa.Column('shadow_intensity', sa.String(length=50), nullable=True),
    sa.Column('default_weather', sa.String(length=100), nullable=True),
    sa.Column('time_period', sa.String(length=100), nullable=True),
    sa.Column('typical_time_of_day', sa.String(length=50), nullable=True),
    sa.Column('season', sa.String(length=50), nullable=True),
    sa.Column('key_elements', sa.JSON(), nullable=True),
    sa.Column('decorations', sa.Text(), nullable=True),
    sa.Column('furniture', sa.Text(), nullable=True),
    sa.Column('vegetation', sa.Text(), nullable=True),
    sa.Column('props', sa.JSON(), nullable=True),
    sa.Column('scale', sa.String(length=100), nullable=True),
    sa.Column('camera_suggestions', sa.JSON(), nullable=True),
    sa.Column('first_appearance_page', sa.Integer(), nullable=True),
    sa.Column('first_appearance_chapter', sa.Integer(), nullable=True),
    sa.Column('appearance_count', sa.Integer(), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=True),
    sa.Column('reference_image_url', sa.String(length=500), nullable=True),
    sa.Column('reference_prompt', sa.Text(), nullable=True),
    sa.Column('base_prompt', sa.Text(), nullable=True),
    sa.Column('embedding_vector', sa.JSON(), nullable=True),
    sa.Column('is_established', sa.String(length=1), nullable=True),
    sa.Column('generation_count', sa.Integer(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenes_book_id'), ['book_id'], unique=False)
        batch_op.create_index('ix_scenes_book_id_name', ['book_id', 'name'], unique=False)
        batch_op.create_index('ix_scenes_setting_type', ['setting_type'], unique=False)

    op.create_table('story_objects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('book_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('appearance', sa.Text(), nullable=True),
    sa.Column('materials', sa.Text(), nullable=True),
    sa.Column('colors', sa.JSON(), nullable=True),
    sa.Column('size', sa.String(length=100), nullable=True),
    sa.Column('shape', sa.String(length=100), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('markings', sa.Text(), nullable=True),
    sa.Column('texture', sa.String(length=100), nullable=True),
    sa.Column('condition', sa.String(length=100), nullable=True),
    sa.Column('special_properties', sa.JSON(), nullable=True),
    sa.Column('effects', sa.Text(), nullable=True),
    sa.Column('aura', sa.String(length=100), nullable=True),
    sa.Column('owner_character_id', sa.String(length=36), nullable=True),
    sa.Column('owner_name', sa.String(length=200), nullable=True),
    sa.Column('first_appearance_page', sa.Integer(), nullable=True),
    sa.Column('first_appearance_chapter', sa.Integer(), nullable=True),
    sa.Column('appearance_count', sa.Integer(), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=True),
    sa.Column('reference_image_url', sa.String(length=500), nullable=True),
    sa.Column('reference_prompt', sa.Text(), nullable=True),
    sa.Column('base_prompt', sa.Text(), nullable=True),
    sa.Column('embedding_vector', sa.JSON(), nullable=True),
    sa.Column('is_established', sa.String(length=1), nullable=True),
    sa.Column('generation_count', sa.Integer(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('story_objects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_story_objects_book_id'), ['book_id'], unique=False)
        batch_op.create_index('ix_story_objects_book_id_name', ['book_id', 'name'], unique=False)
        batch_op.create_index('ix_story_objects_category', ['category'], unique=False)
        batch_op.create_index('ix_story_objects_owner', ['owner_character_id'], unique=False)

    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story_objects', schema=None) as batch_op:
        batch_op.drop_index('ix_story_objects_owner')
        batch_op.drop_index('ix_story_objects_category')
        batch_op.drop_index('ix_story_objects_book_id_name')
        batch_op.drop_index(batch_op.f('ix_story_objects_book_id'))

    op.drop_table('story_objects')
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.drop_index('ix_scenes_setting_type')
        batch_op.drop_index('ix_scenes_book_id_name')
        batch_op.drop_index(batch_op.f('ix_scenes_book_id'))

    op.drop_table('scenes')
    with op.batch_alter_table('prompt_history', schema=None) as batch_op:
        batch_op.drop_index('ix_prompt_history_text_hash')
        batch_op.drop_index('ix_prompt_history_status')
        batch_op.drop_index(batch_op.f('ix_prompt_history_page_number'))
        batch_op.drop_index(batch_op.f('ix_prompt_history_page_id'))
        batch_op.drop_index(batch_op.f('ix_prompt_history_chapter_id'))
        batch_op.drop_index('ix_prompt_history_book_page')
        batch_op.drop_index(batch_op.f('ix_prompt_history_book_id'))

    op.drop_table('prompt_history')
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_index('ix_characters_importance')
        batch_op.drop_index('ix_characters_book_id_name')
        batch_op.drop_index(batch_op.f('ix_characters_book_id'))

    op.drop_table('characters')
    # ### end Alembic commands ###
